version: '3'
  
services:
  mantisbt:
    build:
      context: .
    container_name: mantisbt
    ports:
      - "8989:80"
    restart: always
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bugtracker
      - MYSQL_USER=mantisbt
      - MYSQL_PASSWORD=mantisbt
    restart: always

