version: '3'

services:
  django:
    build:
      context: .
    container_name: easybuggy
    restart: always
    command: python /project/easybuggy/manage.py runserver 0.0.0.0:8888
    ports:
      - "8888:8888"
    stdin_open: true
    tty: true

