version: '3'

services:
  web:
    container_name: rails_sample.web
    build:
      context: .
    ports:
      - "3000:3000"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
      - ./contrast_security.yaml:/myapp/config/contrast_security.yaml
    depends_on:
      - db
  db:
    container_name: rails_sample.db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

