version: '3'

services:
  django:
    build:
      context: .
    container_name: django_simple
    restart: always
    command: python /project/sample/manage.py runserver 0.0.0.0:8080
    ports:
      - "8080:8080"
    tty: true
    stdin_open: true

